import {
	GENERATOR_IDS,
	createGeneratorResultSchema,
	generatedTextSchema,
	personGeneratorRequestSchema,
} from "./contracts";
import { generateSeries, pickFromList, resolveLocale } from "./helpers";

const textResultSchema = createGeneratorResultSchema(generatedTextSchema);

const streetNames = [
	"Maple Street",
	"Oak Avenue",
	"Cedar Lane",
	"Sunset Boulevard",
	"River Road",
	"Market Street",
	"Pine Court",
	"Hillcrest Drive",
	"Main Street",
	"Park Avenue",
	"Broadway",
	"Market Street",
	"High Street",
	"King Street",
	"Queen Street",
	"Prince Street",
	"Princess Street",
	"First Street",
	"Mars next to the Moon",
	"Jupiter Street",
	"Saturn Street",
	"Uranus Street",
	"Neptune Street",
	"Pluto Street",
	"Mercury Street",
	"Venus Street",
	"Earth Street",
	"Not so far away",
	"Not so close",
	"Even more far away",
	"Next street street",
	"No name street",
	"1st Street",
	"2nd Street",
	"3rd Street",
	"4th Street",
	"5th Street",
	"6th Street",
	"7th Street",
	"8th Street",
	"9th Street",
	"10th Street",
	"Lic. Jorge Eusebio",
	"Lic. Maria Jose",
	"404 Not Found Lane",
	"Infinite Loop Drive",
	"Null Pointer Boulevard",
	"Syntax Error Court",
	"Merge Conflict Way",
	"Hotfix Highway",
	"Rubber Duck Plaza",
	"Production on Friday Street",
	"Works on My Machine Road",
	"Someone Elses Problem Avenue",
	"Temporary Permanent Street",
	"Just One More Tab Lane",
	"Ship It Already Boulevard",
	"Probably Fine Court",
] as const;

const cities = [
	"Austin",
	"Seattle",
	"Brooklyn",
	"Miami",
	"Toronto",
	"Madrid",
	"Bogota",
	"Santiago de Chile",
	"Santiago de Compostela",
	"Mexico City",
	"Aguascalientes",
	"Los Cabos",
	"Tijuana",
	"Cancun",
	"Puerto Vallarta",
	"Mazatlan",
	"Merida",
	"Querétaro",
	"Monterrey",
	"Guadalajara",
	"Zapopan",
	"Tepic",
	"Culiacan",
	"Hermosillo",
	"Chihuahua",
	"Saltillo",
	"Cd. Juarez",
	"Cd. Obregon",
	"Cd. Victoria",
	"Cd. Mante",
	"Bacobampo",
	"Guadalupe",
	"San Luis Potosi",
	"San Cristobal de las Casas",
	"San Cristobal de la Laguna",
	"San Cristobal de la Sierra",
	"Pinal de Amoles",
	"Poncitlan",
	"Puerto Vallarta",
	"Puerto Escondido",
	"Puerto Morelos",
	"Puerto Aventuras",
	"Puerto Vallarta",
	"Huatulco",
	"Vigo",
	"Puerto de la Cruz",
	"Pontevedra",
	"Ponferrada",
	"A Coruna",
	"Ourense",
	"Lugo",
	"Oviedo",
	"Gijon",
	"Santander",
	"Cantabria",
	"Asturias",
	"Flavortown",
	"Stack Overflow",
	"Silicon Alley",
	"Nowhere",
	"Somewhere",
	"Error 404",
	"npm install",
	"localhost",
	"Middle of Nowhere",
	"East Westwood",
	"North Southville",
	"Lower Upperton",
	"New New York",
	"Old New York",
] as const;

const states = [
	"California",
	"Texas",
	"Florida",
	"New York",
	"Washington",
	"Ontario",
	"Jalisco",
	"Madrid",
	"Aguascalientes",
	"Baja California",
	"Baja California Sur",
	"Campeche",
	"Chiapas",
	"Chihuahua",
	"Coahuila",
	"Colima",
	"Durango",
	"Guanajuato",
	"Guerrero",
	"Hidalgo",
	"Jalisco",
	"Mexico City",
	"Michoacan",
	"Morelos",
	"Nayarit",
	"Nuevo Leon",
	"Oaxaca",
	"Puebla",
	"Queretaro",
	"Quintana Roo",
	"San Luis Potosi",
	"Sinaloa",
	"Sonora",
	"Tabasco",
	"Tamaulipas",
	"Tlaxcala",
	"Veracruz",
	"Yucatan",
	"Zacatecas",
	"Seattle",
	"Miami",
	"New York",
	"Los Angeles",
	"Chicago",
	"Houston",
	"Phoenix",
	"Philadelphia",
	"San Antonio",
	"San Diego",
	"Dallas",
	"San Jose",
	"Austin",
	"Jacksonville",
	"Fort Worth",
	"Columbus",
	"Charlotte",
	"Indianapolis",
	"Seattle",
	"Denver",
	"Washington",
	"Boston",
	"El Paso",
	"Nashville",
	"Detroit",
	"Galicia",
	"Catalonia",
	"Valencian Community",
	"Aragon",
	"Asturias",
	"Basque Country",
	"Canary Islands",
	"Castile and León",
	"Castile-La Mancha",
	"Extremadura",
	"Murcia",
	"Navarra",
	"La Rioja",
	"Andalucia",
	"State of Confusion",
	"Undefined",
	"localhost",
	"Tab Limit Exceeded",
	"Merge Conflict Valley",
	"Production Panic",
	"Works On My Machine",
	"404 Not Found",
	"Null Island",
] as const;

const countries = [
	"United States",
	"Canada",
	"Mexico",
	"Spain",
	"Germany",
	"Argentina",
	"Chile",
	"Colombia",
	"Peru",
	"Ecuador",
	"France",
	"Bolivia",
	"Venezuela",
	"Brazil",
	"Uruguay",
	"Paraguay",
	"Guatemala",
	"Honduras",
	"Nicaragua",
	"Costa Rica",
	"Panama",
	"El Salvador",
	"Haiti",
	"Dominican Republic",
	"Jamaica",
	"Cuba",
	"Puerto Rico",
	"Dominica",
	"Trinidad and Tobago",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Saint Kitts and Nevis",
	"Antigua and Barbuda",
	"Barbados",
	"Grenada",
	"Belize",
	"Portugal",
	"Ireland",
	"Israel",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"United Kingdom",
	"Australia",
	"New Zealand",
	"South Africa",
	"Nigeria",
	"Kenya",
	"South Korea",
	"Japan",
	"China",
	"Russia",
	"Ukraine",
	"Poland",
	"Czech Republic",
	"Slovakia",
	"Hungary",
	"Romania",
	"Bulgaria",
	"Greece",
	"Netherlands",
	"Belgium",
	"Sweden",
	"Norway",
	"Denmark",
	"Finland",
	"Iceland",
	"Estonia",
	"Latvia",
	"Lithuania",
	"Croatia",
	"Slovenia",
	"Serbia",
	"Montenegro",
	"Albania",
	"Kosovo",
	"Macedonia",
	"Bosnia and Herzegovina",
	"Moldova",
	"Georgia",
	"Armenia",
	"Azerbaijan",
	"Bahrain",
	"Qatar",
	"Saudi Arabia",
	"United Arab Emirates",
	"Israel",
	"Jordan",
	"Lebanon",
	"Syria",
	"Pakistan",
	"India",
	"Bangladesh",
	"Nepal",
	"Sri Lanka",
	"Maldives",
	"Myanmar",
	"Thailand",
	"Vietnam",
	"Philippines",
	"Malaysia",
	"Singapore",
	"Indonesia",
	"Madagascar",
	"Mauritius",
	"Reunion",
	"Mayotte",
	"Comoros",
	"Seychelles",
	"Sao Tome and Principe",
	"Equatorial Guinea",
	"Gabon",
	"Rwanda",
	"Burundi",
	"Togo",
	"Benin",
	"Mauritania",
	"Niger",
	"Chad",
	"Central African Republic",
	"Cape Verde",
	"Narnia",
	"Wakanda",
	"Genovia",
	"The Shire",
	"Springfield",
	"Bikini Bottom",
	"Latveria",
	"Gotham",
	"Hyrule",
	"Raccoon City",
	"Elbonia",
	"Freedonia",
] as const;

function randomInt(max: number): number {
	return Math.floor(Math.random() * max);
}

export function buildCity(): string {
	return pickFromList(cities);
}

export function buildState(): string {
	return pickFromList(states);
}

export function buildCountry(): string {
	return pickFromList(countries);
}

export function buildZip(): string {
	return `${10000 + randomInt(90000)}`;
}

export function buildAddress(): string {
	return `${100 + randomInt(9900)} ${pickFromList(streetNames)}`;
}

export function generateAddresses(input: unknown = {}) {
	const request = personGeneratorRequestSchema.parse(input);
	const locale = resolveLocale(request.locale);

	return textResultSchema.parse({
		id: GENERATOR_IDS.ADDRESS,
		locale,
		count: request.count,
		values: generateSeries(request.count, () => buildAddress()),
	});
}

export function generateCities(input: unknown = {}) {
	const request = personGeneratorRequestSchema.parse(input);
	const locale = resolveLocale(request.locale);

	return textResultSchema.parse({
		id: GENERATOR_IDS.CITY,
		locale,
		count: request.count,
		values: generateSeries(request.count, () => buildCity()),
	});
}

export function generateStates(input: unknown = {}) {
	const request = personGeneratorRequestSchema.parse(input);
	const locale = resolveLocale(request.locale);

	return textResultSchema.parse({
		id: GENERATOR_IDS.STATE,
		locale,
		count: request.count,
		values: generateSeries(request.count, () => buildState()),
	});
}

export function generateZips(input: unknown = {}) {
	const request = personGeneratorRequestSchema.parse(input);
	const locale = resolveLocale(request.locale);

	return textResultSchema.parse({
		id: GENERATOR_IDS.ZIP,
		locale,
		count: request.count,
		values: generateSeries(request.count, () => buildZip()),
	});
}

export function generateCountries(input: unknown = {}) {
	const request = personGeneratorRequestSchema.parse(input);
	const locale = resolveLocale(request.locale);

	return textResultSchema.parse({
		id: GENERATOR_IDS.COUNTRY,
		locale,
		count: request.count,
		values: generateSeries(request.count, () => buildCountry()),
	});
}
